// Mocks generated by Mockito 5.4.6 from annotations


import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:flutter_application/models/device_model.dart' as _i4;
import 'package:flutter_application/models/message_model.dart' as _i7;
import 'package:flutter_application/models/resource_model.dart' as _i5;
import 'package:flutter_application/services/database_service.dart' as _i9;
import 'package:flutter_application/services/p2p_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;



class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [P2PService].
///

class MockP2PService extends _i1.Mock implements _i3.P2PService {
  MockP2PService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.DeviceModel> get connectedDevices =>
      (super.noSuchMethod(
            Invocation.getter(#connectedDevices),
            returnValue: <_i4.DeviceModel>[],
          )
          as List<_i4.DeviceModel>);

  @override
  bool get isAdvertising =>
      (super.noSuchMethod(Invocation.getter(#isAdvertising), returnValue: false)
          as bool);

  @override
  bool get isDiscovering =>
      (super.noSuchMethod(Invocation.getter(#isDiscovering), returnValue: false)
          as bool);

  @override
  int get batteryLevel =>
      (super.noSuchMethod(Invocation.getter(#batteryLevel), returnValue: 0)
          as int);

  @override
  List<_i5.ResourceModel> get networkResources =>
      (super.noSuchMethod(
            Invocation.getter(#networkResources),
            returnValue: <_i5.ResourceModel>[],
          )
          as List<_i5.ResourceModel>);

  @override
  _i6.Stream<_i5.ResourceModel> get resourceStream =>
      (super.noSuchMethod(
            Invocation.getter(#resourceStream),
            returnValue: _i6.Stream<_i5.ResourceModel>.empty(),
          )
          as _i6.Stream<_i5.ResourceModel>);

  @override
  _i6.Stream<Map<String, dynamic>> get resourceRequestStream =>
      (super.noSuchMethod(
            Invocation.getter(#resourceRequestStream),
            returnValue: _i6.Stream<Map<String, dynamic>>.empty(),
          )
          as _i6.Stream<Map<String, dynamic>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> initialize(String? userName) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [userName]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> startAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#startAdvertising, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> startDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#startDiscovery, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> stopAdvertising() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertising, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stopDiscovery() =>
      (super.noSuchMethod(
            Invocation.method(#stopDiscovery, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> broadcastData(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastData, [data]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendMessage(String? endpointId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [endpointId, message]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> broadcastEmergencyAlert(String? alertMessage) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEmergencyAlert, [alertMessage]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  List<_i7.MessageModel> getMessageHistory(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageHistory, [endpointId]),
            returnValue: <_i7.MessageModel>[],
          )
          as List<_i7.MessageModel>);

  @override
  List<_i7.MessageModel> getMessageHistoryForDevice(
    String? endpointId,
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageHistoryForDevice, [
              endpointId,
              deviceId,
            ]),
            returnValue: <_i7.MessageModel>[],
          )
          as List<_i7.MessageModel>);

  @override
  _i6.Stream<_i7.MessageModel>? getMessageStream(String? endpointId) =>
      (super.noSuchMethod(Invocation.method(#getMessageStream, [endpointId]))
          as _i6.Stream<_i7.MessageModel>?);

  @override
  _i6.Future<void> broadcastResource(_i5.ResourceModel? resource) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastResource, [resource]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> requestResourcesFromDevice(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#requestResourcesFromDevice, [endpointId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  List<_i5.ResourceModel> getResourcesByDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getResourcesByDevice, [deviceId]),
            returnValue: <_i5.ResourceModel>[],
          )
          as List<_i5.ResourceModel>);

  @override
  List<_i5.ResourceModel> getResourcesByEndpointId(String? endpointId) =>
      (super.noSuchMethod(
            Invocation.method(#getResourcesByEndpointId, [endpointId]),
            returnValue: <_i5.ResourceModel>[],
          )
          as List<_i5.ResourceModel>);

  @override
  _i6.Future<void> requestSpecificResource(
    String? endpointId,
    String? resourceId,
    int? requestedQuantity,
    String? requesterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestSpecificResource, [
              endpointId,
              resourceId,
              requestedQuantity,
              requesterName,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> respondToResourceRequest(
    String? endpointId,
    String? resourceId,
    bool? approved,
    int? quantity,
    String? requesterName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#respondToResourceRequest, [
              endpointId,
              resourceId,
              approved,
              quantity,
              requesterName,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void updateResourceAfterApproval(
    String? resourceId,
    int? requestedQuantity,
    String? requesterName,
  ) => super.noSuchMethod(
    Invocation.method(#updateResourceAfterApproval, [
      resourceId,
      requestedQuantity,
      requesterName,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseService].
///

class MockDatabaseService extends _i1.Mock implements _i9.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i6.Future<void> saveUserProfile({
    required String? name,
    String? role,
    required String? deviceId,
    String? phone,
    String? bloodType,
    String? medicalConditions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [], {
              #name: name,
              #role: role,
              #deviceId: deviceId,
              #phone: phone,
              #bloodType: bloodType,
              #medicalConditions: medicalConditions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> saveEmergencyContact({
    required String? name,
    required String? relation,
    required String? phone,
    required String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveEmergencyContact, [], {
              #name: name,
              #relation: relation,
              #phone: phone,
              #deviceId: deviceId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getEmergencyContacts(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmergencyContacts, [deviceId]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> updateEmergencyContact({
    required int? id,
    required String? name,
    required String? relation,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmergencyContact, [], {
              #id: id,
              #name: name,
              #relation: relation,
              #phone: phone,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteEmergencyContact(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmergencyContact, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveMessage(
    _i7.MessageModel? message,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [message, conversationId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.MessageModel>> getMessages(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId]),
            returnValue: _i6.Future<List<_i7.MessageModel>>.value(
              <_i7.MessageModel>[],
            ),
          )
          as _i6.Future<List<_i7.MessageModel>>);

  @override
  _i6.Future<void> saveUserResource(_i5.ResourceModel? resource) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserResource, [resource]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.ResourceModel>> getUserResources(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserResources, [deviceId]),
            returnValue: _i6.Future<List<_i5.ResourceModel>>.value(
              <_i5.ResourceModel>[],
            ),
          )
          as _i6.Future<List<_i5.ResourceModel>>);

  @override
  _i6.Future<void> deleteResource(String? resourceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteResource, [resourceId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
